### ISSUE TITLE
Optimization with Curricula?

### ISSUE THREAD

**Issue by lynshwoo2022** [SanyeungWang/PML#5]
hi there,
as your paper said, you train thise model following the insight of curriculum learning. Is there any possibility you can release the code of creating dataset?

**Comment by SanyeungWang** [comment]
Hi there,

Thank you for your interest in our work. 

Sure, the code for dividing training courses has been uploaded. By the way, I'm sorry for not paying attention to the issues recently.

Have a nice day!

Best Regards,
Chenyang

**Comment by lynshwoo2022** [comment]
thanks!
